apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster 
spec:
  instances: 3

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised
  
  monitoring:
    enablePodMonitor: true  # Require 1Gi of space
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      volumeMode: Filesystem
      selector:
        matchExpressions:
        - key: volume-type
          operator: In
          values:
          - nfs

