apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-1
  labels:
    volume-type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share
    server: 192.168.0.62
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-2
  labels:
    volume-type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share_one
    server: 192.168.0.62
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-3
  labels:
    volume-type: nfs
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share_two
    server: 192.168.0.62
