apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgadmin.name" . }}-servers
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": {{ .Values.server.name | quote }},
          "Group": {{ .Values.server.group | quote }},
          "Host": {{ .Values.server.host | quote }},
          "Port": {{ .Values.server.port }},
          "MaintenanceDB": {{ .Values.server.maintenanceDb | quote }},
          "Username": {{ .Values.server.username | quote }},
          "SSLMode": {{ .Values.server.sslMode | quote }},
          "ConnectionParameters": {
            "sslmode": {{ .Values.server.sslMode | quote }},
            "connect_timeout": {{ .Values.server.connectTimeout }}
          }
        }
      }
    }
