apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgadmin.name" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgadmin.labels" . | nindent 8 }}
      annotations: {}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "pgadmin.name" . }}
          image: "{{ index .Values "pgadmin" "image" "repository" }}:{{ index .Values "pgadmin" "image" "tag" | default .Chart.AppVersion }}"
          imagePullPolicy: {{ index .Values "pgadmin" "image" "pullPolicy" }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ index .Values "pgadmin" "port" }}
              protocol: TCP
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: {{ .Values.auth.email | quote }}
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.existingSecret }}
                  key: {{ .Values.auth.passwordKey }}
            - name: PGADMIN_LISTEN_PORT
              value: {{ index .Values "pgadmin" "port" | quote }}
            - name: PGADMIN_DISABLE_POSTFIX
              value: "true"
            - name: PGADMIN_REPLACE_SERVERS_ON_STARTUP
              value: "True"
            {{- if not .Values.server.importOnStartup }}
            - name: PGADMIN_SERVER_JSON_FILE
              value: "/dev/null"
            {{- end }}
            - name: PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION
              value: "False"
          {{- if .Values.probes.startup.enabled }}
          startupProbe:
            httpGet:
              path: /misc/ping
              port: http
            failureThreshold: {{ .Values.probes.startup.failureThreshold }}
            periodSeconds: {{ .Values.probes.startup.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.startup.timeoutSeconds }}
          {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /misc/ping
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
          {{- end }}
          resources:
            {{- toYaml (index .Values "pgadmin" "resources") | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath }}
            - name: servers
              mountPath: /pgadmin4/servers.json
              subPath: servers.json
              readOnly: true
      volumes:
        - name: servers
          configMap:
            name: {{ include "pgadmin.name" . }}-servers
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pgadmin.name" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
