{{- if .Values.infra.enabled }}
{{- range .Values.global.namespaces }}
{{- $namespace := . }}
{{- $env := "development" }}
{{- if contains "prod" . }}
{{- $env = "production" }}
{{- else if contains "stg" . }}
{{- $env = "staging" }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Values.infra.externalSecret.name | default "infra-env-secrets" }}
  namespace: {{ $namespace }}
  labels:
    {{- include "openbao-secrets-manager.labels" $ | nindent 4 }}
    app.kubernetes.io/component: infra-external-secret
    environment: {{ $env }}
spec:
  refreshInterval: {{ $.Values.infra.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ include "openbao-secrets-manager.secretStoreName" $ }}
    kind: SecretStore
  target:
    name: {{ $.Values.infra.externalSecret.target.name | default "infra-env-secrets" }}
    creationPolicy: {{ $.Values.infra.externalSecret.target.creationPolicy | default "Owner" }}
    template:
      type: {{ $.Values.infra.externalSecret.target.template.type | default "Opaque" }}
      metadata:
        labels:
          {{- include "openbao-secrets-manager.labels" $ | nindent 10 }}
          {{- with $.Values.infra.externalSecret.target.template.metadata.labels }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          environment: {{ $env }}
      {{- with $.Values.infra.externalSecret.target.template.data }}
      data:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.infra.externalSecret.target.template.mergePolicy }}
      mergePolicy: {{ . }}
      {{- end }}
  dataFrom:
    - extract:
        {{- if eq $env "production" }}
        key: {{ $.Values.infra.production.remoteRef.key | default "devops/production" }}
        {{- else if eq $env "staging" }}
        key: {{ $.Values.infra.staging.remoteRef.key | default "devops/staging" }}
        {{- else }}
        key: {{ $.Values.infra.development.remoteRef.key | default "devops/development" }}
        {{- end }}
{{- end }}
{{- end }}
