# OpenBao Cluster Secrets Manager - ArgoCD Application
# 클러스터 레벨 시크릿(ClusterSecretStore, ClusterExternalSecret) 관리
# 모든 환경(staging, production)에서 동일한 설정 사용

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-cluster-secrets-manager
  namespace: argocd
  labels:
    app.kubernetes.io/name: openbao-cluster-secrets-manager
    app.kubernetes.io/component: cluster-secrets
  annotations:
    # 가장 먼저 배포 (다른 애플리케이션들이 시크릿을 참조하기 전에)
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git
    targetRevision: main
    path: helm/shared-configs/openbao-cluster-secrets-manager
    helm:
      valueFiles:
        - values.yaml

  # 클러스터 레벨 리소스 (ClusterSecretStore, ClusterExternalSecret)
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 5

  ignoreDifferences:
    - group: "external-secrets.io"
      kind: ClusterExternalSecret
      jsonPointers:
        - /status
    - group: "external-secrets.io"
      kind: ClusterSecretStore
      jsonPointers:
        - /status

  info:
    - name: Purpose
      value: "클러스터 레벨 전역 시크릿 관리 (GITHUB 인증 등)"
    - name: SecretPath
      value: "secret/server/cluster"
    - name: TargetNamespaces
      value: "plate-stg, plate-prod"
