# OpenBao Secrets Manager - Production 환경 ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-secrets-manager-prod
  namespace: argocd  # ArgoCD가 설치된 네임스페이스
  labels:
    app.kubernetes.io/name: openbao-secrets-manager
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: shared-config
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"         # 애플리케이션보다 먼저 배포 (Secret 관리자가 먼저 초기화되어야 함)
    argocd.argoproj.io/sync-options: Validate=true  # 리소스 검증 활성화
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # 삭제 시 모든 리소스 정리
spec:
  # ArgoCD 프로젝트 지정 (default는 모든 클러스터/네임스페이스 접근 가능)
  project: default

  # Git 소스 설정
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git  # Git 저장소 URL
    targetRevision: main                                    # 추적할 브랜치/태그 (main 브랜치 자동 추적)
    path: helm/shared-configs/openbao-secrets-manager       # Helm 차트 경로
    helm:
      # Production 환경 전용 values 파일 사용
      valueFiles:
        - values.yaml             # 기본 values
        - values-production.yaml  # Production 환경 오버라이드

  # 배포 대상 클러스터 및 네임스페이스
  destination:
    server: https://kubernetes.default.svc  # 클러스터 API 서버 (in-cluster)
    namespace: plate-prod                   # 배포될 네임스페이스

  # 동기화 정책 (Production은 보수적 설정)
  syncPolicy:
    # 자동 동기화 설정 (Git Push 시 자동 반영, 기본 폴링 주기 3분)
    automated:
      prune: false        # Production은 자동 삭제 비활성화 (보수적 운영)
      selfHeal: true      # 클러스터에서 수동 변경 시 Git 상태로 자동 복구
      allowEmpty: false   # 빈 리소스 세트 동기화 방지 (안전 장치)
    
    # 동기화 옵션
    syncOptions:
      - CreateNamespace=false           # 네임스페이스는 사전 생성되어야 함 (애플리케이션이 먼저 생성)
      - PrunePropagationPolicy=foreground  # 삭제 시 종속 리소스를 먼저 삭제한 후 부모 리소스 삭제
      - PruneLast=true                     # 다른 리소스 적용 후 prune 실행
      - Validate=true                      # 리소스 검증 활성화 (Production 안전 장치)
    
    # 동기화 실패 시 재시도 정책 (Production은 더 긴 대기 시간)
    retry:
      limit: 3              # 최대 재시도 횟수 (Production은 적게 설정)
      backoff:
        duration: 10s       # 첫 재시도 대기 시간 (Staging보다 김)
        factor: 2           # 재시도마다 대기 시간 배수 증가 (10s → 20s → 40s)
        maxDuration: 5m     # 최대 대기 시간 (Staging보다 김)

  # Git 이력 보관 개수 (Production은 더 많은 이력 보관)
  revisionHistoryLimit: 10

  # 특정 필드에 대한 변경 무시 설정 (Secret 데이터는 외부에서 관리됨)
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data  # Secret data 필드 변경은 무시 (외부 시스템이 관리)
    - group: "external-secrets.io"
      kind: ExternalSecret
      jsonPointers:
        - /status  # ExternalSecret status 필드 변경은 무시 (컴트롤러가 관리)

  # ArgoCD UI에 표시될 애플리케이션 정보
  info:
    - name: Purpose
      value: "프로덕션 환경 OpenBao 시크릿 관리"
    - name: Environment
      value: "production"