# OpenBao Secrets Manager - Staging 환경 ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-secrets-manager-stg
  namespace: argocd
  labels:
    app.kubernetes.io/name: openbao-secrets-manager
    app.kubernetes.io/instance: staging
    app.kubernetes.io/component: shared-config
    environment: staging
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git
    targetRevision: main
    path: helm/shared-configs/openbao-secrets-manager
    helm:
      # Staging 환경 전용 values 파일 사용
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plate-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: "external-secrets.io"
      kind: ExternalSecret
      jsonPointers:
        - /status
  info:
    - name: Purpose
      value: "스테이징 환경 OpenBao 시크릿 관리"
    - name: Environment
      value: "staging"