# OpenBao Admin Secrets Manager - Staging 환경
# Admin 애플리케이션 시크릿 관리 (admin/staging KV 경로)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-plate-admin-secrets-manager-stg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: openbao-plate-admin-secrets-manager
    app.kubernetes.io/instance: staging
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git
    path: helm/shared-configs/openbao-plate-admin-secrets-manager
    targetRevision: main
    helm:
      valueFiles:
        - values-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: plate-stg

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: "external-secrets.io"
      kind: ExternalSecret
      jsonPointers:
        - /status

  revisionHistoryLimit: 5

  info:
    - name: "Environment"
      value: "Staging"
    - name: "OpenBao KV Path"
      value: "admin/staging"
    - name: "Description"
      value: "Admin 애플리케이션 시크릿 관리 - Staging"
