# OpenBao Secrets Manager - Production 환경 ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-secrets-manager-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: openbao-secrets-manager
    app.kubernetes.io/instance: production
    app.kubernetes.io/component: shared-config
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Validate=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git
    targetRevision: main
    path: helm/shared-configs/openbao-secrets-manager
    helm:
      # Production 환경 전용 values 파일 사용
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plate-prod
  syncPolicy:
    automated:
      prune: false  # More conservative for production
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - Validate=true
    retry:
      limit: 3  # Fewer retries for production
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 10  # Keep more history for production
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: "external-secrets.io"
      kind: ExternalSecret
      jsonPointers:
        - /status
  info:
    - name: Purpose
      value: "OpenBao secrets management for production environment"
    - name: Environment
      value: "production"