# OpenBao Admin Secrets Manager - Production 환경
# Admin 애플리케이션 시크릿 관리 (admin/production KV 경로)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openbao-admin-secrets-manager-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: openbao-admin-secrets-manager
    app.kubernetes.io/instance: production
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git
    path: helm/shared-configs/openbao-admin-secrets-manager
    targetRevision: main
    helm:
      valueFiles:
        - values-production.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: plate-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: "external-secrets.io"
      kind: ExternalSecret
      jsonPointers:
        - /status

  revisionHistoryLimit: 5

  info:
    - name: "Environment"
      value: "Production"
    - name: "OpenBao KV Path"
      value: "admin/production"
    - name: "Description"
      value: "Admin 애플리케이션 시크릿 관리 - Production"
