# Plate Web - Production 환경 ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-web-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: plate-web
    app.kubernetes.io/instance: production
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git # 실제 Git Repository URL로 변경 필요
    path: helm/applications/plate-web
    targetRevision: main
    helm:
      # Production 환경 전용 values 파일 사용
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plate-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Environment"
      value: "Production"
    - name: "Domain"
      value: "cocdev.co.kr, www.cocdev.co.kr"
    - name: "Description"
      value: "Plate Web Application - Production Environment"
