# Plate Cache - Production
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-cache-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Storage 먼저 생성
  labels:
    app.kubernetes.io/name: plate-cache
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git
    path: helm/applications/plate-cache
    targetRevision: main
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
  revisionHistoryLimit: 3
  info:
    - name: Purpose
      value: "Plate Container Cache Storage (Production)"
