# Plate Cache - Container Builder PVC ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-cache
  namespace: argocd  # ArgoCD가 설치된 네임스페이스
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Storage를 먼저 생성 (낮은 sync-wave가 먼저 배포됨)
  labels:
    app.kubernetes.io/name: plate-cache
spec:
  # ArgoCD 프로젝트 지정 (default는 모든 클러스터/네임스페이스 접근 가능)
  project: default

  # Git 소스 설정
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git  # Git 저장소 URL
    path: helm/applications/plate-cache                     # Helm 차트 경로
    targetRevision: main                                    # 추적할 브랜치/태그 (main 브랜치 자동 추적)

  # 배포 대상 클러스터 및 네임스페이스
  destination:
    server: https://kubernetes.default.svc  # 클러스터 API 서버 (in-cluster)
    namespace: devops-tools                 # 배포될 네임스페이스 (DevOps 도구 전용)

  # 동기화 정책
  syncPolicy:
    # 자동 동기화 설정 (Git Push 시 자동 반영, 기본 폴링 주기 3분)
    automated:
      prune: true      # Git에서 삭제된 리소스를 클러스터에서도 자동 삭제
      selfHeal: true   # 클러스터에서 수동 변경 시 Git 상태로 자동 복구

    # 동기화 옵션
    syncOptions:
      - CreateNamespace=true      # 네임스페이스가 없으면 자동 생성
      - ApplyOutOfSyncOnly=true   # 변경된 리소스만 적용 (성능 최적화)

  # Git 이력 보관 개수 (롤백 가능한 리비전 수, 캐시는 짧게 유지)
  revisionHistoryLimit: 3

  # ArgoCD UI에 표시될 애플리케이션 정보
  info:
    - name: Purpose
      value: "Plate Container Cache Storage"
