# Plate API - Staging 환경 ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-api-stg
  namespace: argocd
  labels:
    app.kubernetes.io/name: plate-api
    app.kubernetes.io/instance: staging
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git # 실제 Git Repository URL로 변경 필요
    path: helm/applications/plate-api
    targetRevision: main
    helm:
      # Staging 환경 전용 values 파일 사용
      valueFiles:
        - values-stg.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: plate-stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Environment"
      value: "Staging"
    - name: "Domain"
      value: "cocdev.co.kr/api (staging)"
    - name: "Description"
      value: "Plate API Server - Staging Environment"
