# Plate Admin - Staging 환경 ArgoCD Application

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plate-admin-stg
  namespace: argocd
  labels:
    app.kubernetes.io/name: plate-admin
    app.kubernetes.io/instance: staging
    environment: staging
spec:
  project: default

  # Git 소스 설정
  source:
    repoURL: https://github.com/kimjoongwon/prj-devops.git
    path: helm/applications/plate-admin
    targetRevision: main
    helm:
      valueFiles:
        - values-stg.yaml

  # 배포 대상 클러스터 및 네임스페이스
  destination:
    server: https://kubernetes.default.svc
    namespace: plate-stg

  # 동기화 정책
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  revisionHistoryLimit: 10

  info:
    - name: "Environment"
      value: "Staging"
    - name: "Domain"
      value: "admin.stg.cocdev.co.kr"
    - name: "Description"
      value: "Plate Admin - Staging Environment (Next.js)"
