apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tempo.fullname" . }}-config
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
data:
  tempo.yaml: |
    server:
      http_listen_port: {{ .Values.service.queryPort }}
      grpc_listen_port: 9095

    distributor:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:{{ .Values.service.otlpGrpcPort }}
            http:
              endpoint: 0.0.0.0:{{ .Values.service.otlpHttpPort }}

    ingester:
      lifecycler:
        ring:
          replication_factor: 1
          kvstore:
            store: inmemory
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: {{ .Values.retention }}

    storage:
      trace:
        backend: local
        wal:
          path: /var/tempo/wal
        local:
          path: /var/tempo/traces

    querier:
      frontend_worker:
        frontend_address: 127.0.0.1:9095
