apiVersion: apps/v1
kind: Deployment
metadata:
  name: prj-docs-web
  labels:
    app.kubernetes.io/name: prj-docs-web
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: prj-docs-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prj-docs-web
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 3
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
