apiVersion: v2
name: pgadmin
description: pgAdmin 웹 대시보드용 Helm 차트
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - postgres
  - pgadmin
  - database
  - admin
home: https://cocdev.co.kr
sources:
  - https://github.com/kimjoongwon/prj-devops
maintainers:
  - name: Plate Team
    email: dev@cocdev.co.kr
